# Generated by Django 6.0.4 on 2026-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Healthy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
